spring:
  application:
    name: notifier-service

  jpa:
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog.yaml
    default-schema: notifier_service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=notifier_service&options=-c%20timezone=UTC
    username: secret
    password: secret
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20

  ai:
    openai:
      base-url: ${NIM_API_URL:https://integrate.api.nvidia.com}
      api-key: ${NIM_API_KEY:}
      chat:
        options:
          model: meta/llama-3.1-8b-instruct
          max-tokens: 500
          temperature: 0.8
      embedding:
        enabled: false

app:
  version: ${APP_VERSION:0.0.0}
